version: '2.1'

services:
  db:
    env_file: user_info.env
    image: postgres
    volumes:
      - 'postgres_confluence:/var/lib/postgresql/data'

  confluence:
    image: blacklabelops/confluence
    ports:
      - '8090:8090'
      - '8091:8091'
    links:
      - 'db:postgres'

volumes:
  postgres_confluence:
